apiVersion: grofers.com/v1
kind: CeleryApplication
metadata:
  name: celery-obj
spec:
  celery_config:
    image: brainsam/pgbouncer:1.12.0
    replicas: 2
    app_name: celery-operator-object
    worker_class: worker
    queue_name: high_priority
    log_level: info
    concurrency: 2
    max_tasks_per_child: 10000
    resources:
      limits:
        cpu: '1.1'
        memory: 2.2Gi
      requests:
        cpu: '1'
        memory: 2.0Gi
  flower_config:
    flower: 1