apiVersion: v1
kind: Service
metadata:
  name: "{app_name}-flower"
  namespace: "{namespace}"
  labels:
    app: "{app_name}-flower"
spec:
  ports:
  - port: "{flower_port}"
    protocol: TCP
  selector:
    run: "{app_name}-flower"