apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: celeryapplications.grofers.com
spec:
  scope: Namespaced
  group: grofers.com
  names:
    kind: CeleryApplication
    plural: celeryapplications
    singular: celeryapplication
    shortNames:
      - celery
      - capps
      - capp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                app_name:
                  type: string
                celery_app:
                  type: string
                image:
                  type: string
                worker_name:
                  type: string
                celery_config:
                  type: object
                  properties:
                    num_of_workers:
                      type: integer
                    queues:
                      type: string
                    loglevel:
                      type: string
                    concurrency:
                      type: integer
                    max_tasks_per_child:
                      type: integer
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                  x-kubernetes-preserve-unknown-fields: true
                flower_config:
                  type: object
                  properties:
                    replicas:
                      type: integer
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Duration
          type: string
          priority: 0
          jsonPath: .spec.duration
          description: For how long the pod should sleep.
        - name: Children
          type: string
          priority: 0
          jsonPath: .status.create_fn.children
          description: The children pods created.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_fn.message
          description: As returned from the handler (sometimes).