apiVersion: grofers.com/v1
kind: CeleryApplication
metadata:
  name: example-celery-obj
spec:
  app_name: celery-crd-example
  celery_app: 'app:celery_app'
  image: example-image
  worker_name: example-celery-worker
  celery_config:
    num_of_workers: 2
    queues: high_priority
    loglevel: info
    concurrency: 2
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  flower_config:
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"